'''title'''
__title__ = 'pynoveldl'
'''description'''
__description__ = 'NovelDL: Search and download novels from some specific websites'
'''url'''
__url__ = 'https://github.com/CharlesPikachu/noveldl'
'''version'''
__version__ = '0.1.1'
'''author'''
__author__ = 'Charles'
'''email'''
__email__ = 'charlesblwx@gmail.com'
'''license'''
__license__ = 'Apache License 2.0'
'''copyright'''
__copyright__ = 'Copyright 2022 Charles'